# site properties and page defaults
<<<<<<< HEAD
title: CENG Machine Learning and Computer Vision Lab
subtitle: by the Greene Lab
description: An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
header: images/estu_background.png
footer: images/estu_background.png
=======
title: estu-mlcvDESCRIPTION=An engaging 1-3 sentence description of your lab.
subtitle: 
description: 
header: images/background.jpg
footer: images/background.jpg
>>>>>>> 7bd99c7adb161f5eaaf20df6581d08bd3c2359f9
proofer: false

# site social media and other links
links:
  email: contact@estu-mlcvDESCRIPTION=An engaging 1-3 sentence description of your lab..com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: estu-mlcvDESCRIPTION=An engaging 1-3 sentence description of your lab.
  twitter: estu-mlcvDESCRIPTION=An engaging 1-3 sentence description of your lab.
  youtube: estu-mlcvDESCRIPTION=An engaging 1-3 sentence description of your lab.

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
